name: Daily Vacancy Search

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Запуск поиска вакансий
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: |
          python main.py
